src/components/RestaurantDetail/Reviews.js

Reviews showing up once they are submitted without refreshing page

Updated Reviews bug

---

src/components/Navigation/NavBar.js

Profile button switches between sign in/sign up if user is not logged in and my profile/log out if user is logged in

Logout functionality

---

src/components/MyProfile/Event.js
src/components/Navigation/NavBar.js

added styling for edit and cancel buttons in event cards, need to work on functionality

Edit/Cancel Buttons for events

---

src/components/RestaurantDetail/UserLike.js

added tooltip when hovering on user like, need to add logic to send message and add friend

Add friend/ message on hover

---

src/App.js
src/components/OutreachButtons.js
src/components/ProfileCard.js
src/components/RestaurantDetail/UserLike.js

fixed some routes in Appjs, simplified ProfileCard for reutilization, changed modal from ProfileCard to UserLike, changed Outreach buttons to its own component

Outreach, ProfileCard and UserLike

---

src/App.js
src/components/LoginSignUp/LogIn.js
src/components/LoginSignUp/SignUp.js
src/components/MessageCenter/MessageCenter.js
src/components/Navigation/NavBar.js

changes signUpInfo to loggedInUser, dispatch to dispatchUser and includes axios call to get user data in SignUp.js

builds axios calls for modal in SignUp.js

---

src/App.js
src/components/LoginSignUp/LogIn.js
src/components/LoginSignUp/SignUp.js
src/components/Navigation/NavBar.js
src/components/RestaurantCard.js
src/components/UserProfile/UserProfile.js
src/data-and-functions/axiosAll.js

builds logInMessage context in App.js, imports it into RestaurantCard.js and passes it through to LogIn.js using useLocation

builds logInMessage context functionality

---

src/components/MyPage/CoordinateMeetup.js
src/components/MyPage/Event.js

Still working on it, need to fix bug and add functionality to edit

Cancel event function

---

package-lock.json
package.json
src/components/MyPage/CoordinateMeetup.js
src/components/MyPage/Event.js

when editing event, current time and date is displayed and meetup updates when entering new values

Time and date new state when editing

---

package-lock.json
package.json
src/components/SearchResults/Pagination.js
src/components/SearchResults/SearchResults.js

builds new state variables and functions/event handler to get the RestauranCards on the current page and to change the page number and imports Pagination.js in SearchResults.js; builds the page number UL and calculation of total amount of page numbers in Pagination.js

builds Pagination.js file and integrates it into SearchResults.js

---

src/components/MyPage/CoordinateMeetup.js
src/components/MyPage/Event.js

Still need to work on updating event just after submitting changes

events can be edited, and we return to event after submitting changes

---

package-lock.json
package.json
src/components/Messages/Messages.js
src/components/MyPage/CoordinateMeetup.js
src/components/MyPage/Friends.js
src/components/ProfileCard.js
src/components/RestaurantDetail/UserLikes.js

Builds route to get friends in Friends.js and route to get user by ID in ProfileCard.js; updates props in CoordinateMeetup, UserLikes and Messages

builds routes in Friends.js and ProfileCard.js to get friends and user by ID

---

src/components/RestaurantCard.js

Co-Authored-By: Andrew Retherford <105827498+andrewretherford@users.noreply.github.com>

updates liked handler in RestaurantCard.js

---

planning/styling.md
src/index.css

builds tailwind layer components for large containers, buttons and input boxes in index.css

builds more tailwind layer components

---

src/components/MyPage/Friends.js
src/index.css

widens container and adjusts responsive design accordingly

updates styling to Friends component

---

src/components/UserProfile/UserProfile.js

Changed input fields class, and changed minimum height and width for smaller devices

Fix UserProfile component

---

src/components/RestaurantDetail/RestaurantDetail.js
src/components/RestaurantDetail/Review.js
src/components/RestaurantDetail/Reviews.js

Still need to work on users likes and decide colors

Add styling to Review, Reviews and RestaurantDetails

---

src/components/RestaurantCard.js

Background in RestaurantCard was changing color in Event

Remove background from RestaurantCard

---

src/components/MyPage/Event.js
src/components/ProfileCard.js

When clicking in Who's going, a modal displays instead of a tooltip

Change Tooltip for modal in Event

---

src/components/MyPage/Event.js
src/components/ProfileCard.js
src/components/RestaurantDetail/RestaurantDetail.js
src/components/SearchResults/SearchResults.js

Working in adding conditional rendering if there is more than 3 user likes

Fix bug in fontcolor when calling ProfileCard in Event modal

---

src/components/RestaurantDetail/RestaurantDetail.js

also adds border to Reviews section to see separation between userlikes and reviews

Add background to RestaurantDetail

---

src/components/RestaurantDetail/RestaurantDetail.js

Still need to work making it responsive

Add functionality to show all userlikes

---

src/components/MyPage/Event.js

Previously was using different color

Change background in Event card

---

src/components/MyPage/Favorites.js
src/components/MyPage/Itinerary.js
src/components/SearchResults/Pagination.js
src/index.css

Changed height for Favorites and Itinerary in mobile devices, created class to avoid large classname

Fix responsive components

---

src/components/MyPage/Friends.js
src/components/RestaurantDetail/UserLike.js

Also included the message button

Add functionality to render modal for each friend in Friends

---

src/components/RestaurantCard.js

Like button was too close to name

Change width for restaurant names

---

README.md
src/components/FriendRequests/FriendRequestForm.js
src/components/Home/Search.js
src/components/Home/SearchFilters.js
src/components/LoginSignUp/SignUp.js
src/components/Messages/Messages.js
src/components/MyPage/CoordinateMeetup.js
src/components/MyPage/Event.js
src/components/OutreachButtons.js
src/components/RestaurantDetail/RestaurantDetail.js
src/components/RestaurantDetail/ReviewForm.js
src/components/RestaurantDetail/Reviews.js
src/components/RestaurantDetail/UserLike.js
src/data-and-functions/toggleModal.js

adds toggleModal function and imports it to all existing modals

---

src/components/MyPage/Event.js

Whos going modal is too large when there more than 4 people invited

Fix event modal not showing, changed max height
